### ISSUE TITLE
Update Copyright Holder?

### ISSUE THREAD

**Issue by thermokarst** [bokulich-lab/q2-plugin-template#2]
Right now the license file says "Copyright (c) 2021, QIIME 2 development team." - we use that copyright holder ("QIIME 2 development team.") for repos hosted in the QIIME 2 github org (https://github.com/qiime2). There is no problem or issue with listing that copyright holder here in this template, but it seems to me like this template should put a placeholder in for the holder, that way other 3rd-party users of this template don't re-use this copyright holder. For example, if I was developing a plugin on my own, I would list "Copyright (c) 2021, Matthew Ryan Dillon."

**Comment by misialq** [comment]
Thanks @thermokarst! I updated the headers by replacing the reference to the QIIME dev team with a placeholder. I also made a note in the README that those should be adjusted.
